blueprint:
  name: Light DayNight Ambient Lights
  description: Automation to switch lights ambient and daynight, lights (selectable
    value)
  source_url: https://github.com/sirzandt/my-ha-blueprints/blob/main/blueprints/automation/hall_light_daynight_ambient_lights/hall_light_daynight_ambient_lights.yaml
  domain: automation
  input:
    light_target_lights:
      name: Light (as light)
      selector:
        target:
          entity:
          - domain:
            - light
    light_mode:
      name: light_mode
      description: Defines which mode is used ("Uit", "Aan", "Auto", "Ambient", "Schedule")
      selector:
        entity:
          filter:
          - domain:
            - input_select
          multiple: false
          reorder: false
    ambient_level:
      name: ambient_level
      description: Defines the brightness percentage [0, 100] to set a light to when in ambient mode
      default: 20
      selector:
        number:
          min: 0
          max: 100
          step: 1
    is_ambient:
      name: is_ambient
      description: Defines when the ambient times are according a schedule
      selector:
        entity:
          filter:
          - domain:
            - schedule
          multiple: false
          reorder: false
    active_level_value:
      name: active_level_value
      description: Defines the brightness percentage [0, 100] to set a light to when active (in auto mode)
      default: 100
      selector:
        entity:
          filter:
          - domain:
            - input_number
          multiple: false
          reorder: false
    light_level_value:
      name: light_level value
      description: Defines the current light level (0-100) as percentage (for example from a light sensor)
      selector:
        entity:
          filter:
          - domain:
            - input_number
          multiple: false
          reorder: false
    light_level_ambient_threshold:
      name: light_level_ambient_threshold
      description: Defines the light level (0-100) as percentage above which it is considered bright enough to not use ambient light (for example from a light sensor)
      default: 50
      selector:
        number:
          min: 0
          max: 100
          step: 1
    light_level_darker_threshold:
      name: light_level_darker_threshold
      description: Defines the offset with respect to light_level_ambient_threshold to determine whether it is dark enough to switch to ambient mode. For example, if light_level_ambient_threshold is 50 and light_level_darker_threshold is 20, then the light is considered dark if it is below 30 (50 - 20).
      default: 20
      selector:
        number:
          min: 0
          max: 100
          step: 1
    light_level_darker_wait_time:
      name: light_level_darker_wait_time
      description: Defines how long to wait for the light level to be below the dark threshold before switching off the light (when in auto mode). In minutes.
      default: 5
      selector:
        number:
          min: 0
          max: 60
          step: 1
    light_level_lighter_threshold:
      name: light_level_lighter_threshold
      description: Defines the offset with respect to light_level_ambient_threshold to determine whether it is bright enough to switch back from ambient mode. For example, if light_level_ambient_threshold is 50 and light_level_lighter_threshold is 20, then the light is considered bright if it is above 70 (50 + 20).
      default: 20
      selector:
        number:
          min: 0
          max: 100
          step: 1
    light_level_lighter_wait_time:
      name: light_level_lighter_wait_time
      description: Defines how long to wait for the light level to be above the lighter threshold before switching back from ambient mode (when in auto mode). In minutes.
      default: 5
      selector:
        number:
          min: 0
          max: 60
          step: 1
    light_mode_change_delay:
      name: light_mode_change_delay
      description: Defines how long to wait after a change in light_mode before reacting. In seconds.
      default: 0
      selector:
        number:
          min: 0
          max: 3600
          step: 1
    is_ambient_change_delay:
      name: is_ambient_change_delay
      description: Defines how long to wait after a change in is_ambient before reacting. In seconds.
      default: 0
      selector:
        number:
          min: 0
          max: 3600
          step: 1
trigger_variables:
  light_level_darker_wait_time: !input light_level_darker_wait_time
  light_level_lighter_wait_time: !input light_level_lighter_wait_time
  light_level_lighter_threshold: !input light_level_lighter_threshold
  light_level_darker_threshold: !input light_level_darker_threshold
  light_level_ambient_threshold: !input light_level_ambient_threshold
  light_mode_change_delay: !input light_mode_change_delay
  is_ambient_change_delay: !input is_ambient_change_delay
variables:
  light_mode: !input light_mode
  active_level_value: !input active_level_value
  light_level_darker_threshold: !input light_level_darker_threshold
  light_level_value: !input light_level_value
trigger:
# custom trigger when sensor drops below ambient minus darker offset
- trigger: numeric_state
  entity_id: !input light_level_value
  value_template: >
    {{ state.state | float + light_level_darker_threshold | float }}
  below: !input light_level_ambient_threshold
  for:
    hours: 0
    minutes: "{{ light_level_darker_wait_time }}"
    seconds: 0
# custom trigger when sensor rises above ambient plus lighter offset
- trigger: numeric_state
  entity_id: !input light_level_value
  value_template: >
    {{ state.state | float - light_level_lighter_threshold | float }}
  above: !input light_level_ambient_threshold
  for:
    hours: 0
    minutes: "{{ light_level_lighter_wait_time }}"
    seconds: 0
- trigger: state
  entity_id: !input light_mode
  for:
    hours: 0
    minutes: 0
    seconds: "{{ light_mode_change_delay }}"
- trigger: state
  entity_id: !input active_level_value
- trigger: state
  entity_id: !input is_ambient
  for:
    hours: 0
    minutes: 0
    seconds: "{{ is_ambient_change_delay }}"
condition: []
action:
- choose:
  # Mode is on (Aan) - set to the active_level_value
  - conditions:
      - condition: state
        entity_id: !input light_mode
        state: Aan
    sequence:
      - action: light.turn_on
        data:
          brightness_pct: '{{ states[active_level_value].state | float }}'
        target: !input light_target_lights
  # ambient mode conditions: either explicit Ambient mode, schedule mode with
  # an active schedule, or Auto mode with schedule active and the current
  # light level below the ambient threshold.
  - conditions:
      - condition: or
        conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: !input light_mode
                state: Ambient
              - condition: template
                value_template: "{{ states(light_level_value) | float(0) < light_level_ambient_threshold | float }}"
          - condition: and
            conditions:
              - condition: state
                entity_id: !input light_mode
                state: Schedule
              - condition: state
                entity_id: !input is_ambient
                state: 'on'
          - condition: and
            conditions:
              - condition: state
                entity_id: !input light_mode
                state: Auto
              - condition: state
                entity_id: !input is_ambient
                state: 'on'
              - condition: template
                value_template: "{{ states(light_level_value) | float(0) < light_level_ambient_threshold | float }}"
    sequence:
      - action: light.turn_on
        data:
          brightness_pct: !input ambient_level
        target: !input light_target_lights
  default:
    - action: light.turn_off
      target: !input light_target_lights
mode: single
